kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-node-registrar-cfg-systems
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - systems-role
