kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-role-systems
subjects:
  - kind: ServiceAccount
    name: csi-provisioner
roleRef:
  kind: ClusterRole
  name: external-provisioner-runner-systems
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-role-cfg-systems
subjects:
  - kind: ServiceAccount
    name: csi-provisioner
roleRef:
  kind: Role
  name: external-provisioner-cfg-systems
  apiGroup: rbac.authorization.k8s.io
