apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: seagate-exos-x-csi-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Seagate Exos X CSI driver supports Seagate storage systems with 4xx5/5xx5
    controllers (including OEM versions)
  displayName: Seagate Exos X CSI Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - storage
  - csi
  - seagate
  links:
  - name: Seagate Exos X Csi Operator
    url: https://seagate-exos-x-csi-operator.domain
  maturity: alpha
  provider:
    name: Seagate
    url: www.seagate.com
  version: 0.0.0
