# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/storage.seagate.io_seagateexosxcsis.yaml
- volumesnapshots/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
- volumesnapshots/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
- volumesnapshots/snapshot.storage.k8s.io_volumesnapshots.yaml
#+kubebuilder:scaffold:crdkustomizeresource
